# Generated by Django 5.0.6 on 2024-05-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='head',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tariff',
            name='bonus',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='bonustext',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='gigabytes',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='minutes',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='sms',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='speed',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='tv',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
