# Generated by Django 5.0.6 on 2024-05-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_tariff_head_alter_tariff_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='gigabytes',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='minutes',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='sms',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
