# Generated by Django 5.0.6 on 2024-05-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0004_homephonetariff_internettariff_modemtariff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homephonetariff',
            options={'verbose_name': 'Тарифы "Домашние телефоны"', 'verbose_name_plural': 'Тарифы "Домашние телефоны"'},
        ),
        migrations.AlterModelOptions(
            name='internettariff',
            options={'verbose_name': 'Тарифы "Интернет"', 'verbose_name_plural': 'Тарифы "Интернет"'},
        ),
        migrations.AlterModelOptions(
            name='modemtariff',
            options={'verbose_name': 'Тарифы "Модемы"', 'verbose_name_plural': 'Тарифы "Модемы"'},
        ),
        migrations.AlterModelOptions(
            name='smarttariff',
            options={'verbose_name': 'Тарифы "Смарт"', 'verbose_name_plural': 'Тарифы "Смарт"'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Тарифы "Мобильные телефоны"', 'verbose_name_plural': 'Тарифы "Мобильные телефоны"'},
        ),
        migrations.AlterModelOptions(
            name='tvtariff',
            options={'verbose_name': 'Тарифы "Телевидение"', 'verbose_name_plural': 'Тарифы "Телевидение"'},
        ),
        migrations.AddField(
            model_name='tariff',
            name='isFavotite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smarttariff',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название тарифа'),
        ),
        migrations.AlterField(
            model_name='smarttariff',
            name='price',
            field=models.IntegerField(blank=True, default='', null=True, verbose_name='Цена'),
        ),
    ]
