# Generated by Django 5.0.6 on 2024-07-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0005_alter_homephonetariff_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariff',
            old_name='isFavotite',
            new_name='isFavorite',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='gigabytes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='sms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='tv',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
